<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * api_keys (brief §3.2, spec api-keys): named API keys hashed at rest.
 * Generated by doctrine:migrations:diff and hand-trimmed to the api_keys
 * statements — the diff also proposed recreating an unchanged partial index
 * on clicks and renaming the messenger index, which are diff noise, not
 * schema changes of this migration.
 */
final class Version20260912134933 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'api_keys: named API keys per user — SHA-256 hash unique, display prefix, expiry/revocation/last-use timestamps, owner FK with cascade, owner/created index';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE api_keys (id UUID NOT NULL, name VARCHAR(64) NOT NULL, key_hash CHAR(64) NOT NULL, prefix CHAR(8) NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, last_used_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9579321F57BFB971 ON api_keys (key_hash)');
        $this->addSql('CREATE INDEX idx_api_keys_owner_created ON api_keys (user_id, created_at)');
        $this->addSql('CREATE INDEX IDX_9579321FA76ED395 ON api_keys (user_id)');
        $this->addSql('ALTER TABLE api_keys ADD CONSTRAINT FK_9579321FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE api_keys DROP CONSTRAINT FK_9579321FA76ED395');
        $this->addSql('DROP TABLE api_keys');
    }
}
