<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The Doctrine transport table behind Messenger's `failed` queue (FR-CLK-5):
 * messages that exhausted their retries are parked here for
 * messenger:failed:show / messenger:failed:retry. Created by this migration
 * because the transport runs with auto_setup: false — schema never comes from
 * runtime DDL. Columns and index as the bridge's Connection::buildSchemaTable()
 * defines them; the sender notifies consumers with pg_notify, no trigger.
 */
final class Version20260910142101 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'messenger_messages: the Doctrine transport table of the failed queue (add-async-click-logging)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_messenger_messages_queue ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
