<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The Doctrine transport table behind Messenger's `failed` queue (FR-CLK-5):
 * messages that exhausted their retries are parked here for
 * messenger:failed:show / messenger:failed:retry. From this change on the
 * transport runs with auto_setup: false — schema never comes from runtime DDL.
 *
 * Upgrade path: the previous configuration defaulted to auto_setup: true, so a
 * database that ever listed or received a failed message already carries this
 * table (created by the bridge with its generated index name). The migration
 * ADOPTS such a table: CREATE … IF NOT EXISTS keeps the rows, and the bridge's
 * index is renamed to the stable name so no duplicate index is created.
 * Columns and index as the bridge's Connection::buildSchemaTable() defines
 * them; the sender notifies consumers with pg_notify, no trigger.
 *
 * Rollback: the table is KEPT with its rows. It is shared with the transport,
 * which parks messages in its own transactions; a conditional drop would race
 * a message being parked at that moment (the emptiness check cannot see an
 * uncommitted insert, and the drop would then take it down once committed).
 * The previous configuration's auto_setup transport adopts the table as it is;
 * re-applying the migration is idempotent.
 */
final class Version20260910142101 extends AbstractMigration
{
    /** the bridge's generated name (DBAL hashes table and columns); PostgreSQL stores the unquoted identifier lower-cased */
    private const string BRIDGE_INDEX = 'idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750';

    public function getDescription(): string
    {
        return 'messenger_messages: the Doctrine transport table of the failed queue, adopting an auto-created one (add-async-click-logging)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        // an auto-created table carries the bridge's generated index name: give it the stable name instead of adding a second index
        $this->addSql(\sprintf('ALTER INDEX IF EXISTS %s RENAME TO idx_messenger_messages_queue', self::BRIDGE_INDEX));
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_messenger_messages_queue ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // deliberately no DDL: dropping the table would race a message being parked (see the class comment)
        $this->warnIf(true, 'messenger_messages is kept with its rows: the table is shared with the failed transport, which parks messages concurrently; the previous configuration adopts it as it is.');
    }
}
